In [1]:
from data_file.Adult_Census_Income import Adult_Census_Income as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.ablations import MALMAS_random_experiments_without_memory_async

prompt_path_list = global_config.prompt_path_list
task_name = "Adult_Census_Income"
task = "classification"

2025-08-04 15:37:29,273 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.841885  0.862088  0.844196  0.849390  0.009028
DFS           0.857295  0.858713  0.855638  0.857215  0.001256
AutoFeat      0.841885  0.862088  0.844196  0.849390  0.009028
OpenFE        0.841885  0.862088  0.844196  0.849390  0.009028
CAAFE         0.849016  0.878493  0.852612  0.860040  0.013130
OCTree        0.841885  0.862088  0.844196  0.849390  0.009028
LLMFE         0.852541  0.880220  0.847015  0.859925  0.014527

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2     mean       std
xgboost_base  0.841885  0.862088  0.844196  0.84939  0.009028
MALMAS(ours)  0.857623  0.896154  0.849502  0.86776  0.020350

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.841885  0.862088  0.844196  0.849390  0.009028
MALMAS(ours)  0.844836  0.868603  0.844196  0.852545  0.011358
MALMAS(ours)  0.849672  0.870801  0.853897  0.858123  0.009129
MALMAS(ours)  0.865164  0.882496  0.852322  0.866661  0.012364
MALMAS(ours)  0.851967  0.882732  0.848839  0.861179  0.015293
MALMAS(ours)  0.858197  0.871743  0.864925  0.864955  0.005530
MALMAS(ours)  0.848525  0.894584  0.857546  0.866885  0.019930

In [5]:
baseline_summary_auc = run_baseline_experiments(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.841885  0.862088  0.844196  0.849390  0.009028
DFS           0.857295  0.858713  0.855638  0.857215  0.001256
AutoFeat      0.841885  0.862088  0.844196  0.849390  0.009028
OpenFE        0.841885  0.862088  0.844196  0.849390  0.009028
CAAFE         0.860574  0.871703  0.872678  0.868318  0.005491
OCTree        0.844836  0.859655  0.831924  0.845471  0.011330
LLMFE         0.845738  0.868132  0.845439  0.853103  0.010628

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.841885  0.862088  0.844196  0.849390  0.009028
MALMAS(ours)  0.869426  0.888854  0.866003  0.874761  0.010063

In [7]:
baseline_summary_acc = run_baseline_experiments(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.827586  0.819923  0.793103  0.813538  0.014784
DFS           0.808429  0.804598  0.816092  0.809706  0.004779
AutoFeat      0.827586  0.819923  0.793103  0.813538  0.014784
OpenFE        0.827586  0.819923  0.793103  0.813538  0.014784
CAAFE         0.816092  0.819923  0.831418  0.822478  0.006512
OCTree        0.793103  0.823755  0.793103  0.803321  0.014449
LLMFE         0.816092  0.831418  0.800766  0.816092  0.012513

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.827586  0.819923  0.793103  0.813538  0.014784
MALMAS(ours)  0.819923  0.839080  0.808429  0.822478  0.012643

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.841475  0.869152  0.844279  0.851635  0.012439
DFS            0.844918  0.856907  0.858292  0.853372  0.006005
AutoFeat       0.841475  0.869152  0.845937  0.852188  0.012133
OpenFE         0.841475  0.869152  0.844279  0.851635  0.012439
CAAFE          0.849016  0.858987  0.880224  0.862743  0.013014
OCTree         0.831475  0.841366  0.846683  0.839841  0.006301
LLMFE          0.837787  0.871036  0.850249  0.853024  0.013715

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.841475  0.869152  0.844279  0.851635  0.012439
MALMAS(ours)   0.828770  0.885400  0.847595  0.853922  0.023548

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
catboost_base  0.874836  0.881868  0.865091  0.873932  0.006879
DFS            0.867213  0.878571  0.862438  0.869407  0.006767
AutoFeat       0.875492  0.883909  0.868740  0.876047  0.006205
OpenFE         0.874672  0.885008  0.864428  0.874703  0.008402
CAAFE          0.878443  0.893995  0.877819  0.883419  0.007483
OCTree         0.871393  0.873469  0.860199  0.868354  0.005828
LLMFE          0.863115  0.889874  0.866169  0.873053  0.011960

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.874836  0.881868  0.865091  0.873932  0.006879
MALMAS(ours)   0.881148  0.891680  0.880763  0.884530  0.005058

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.861926  0.876923  0.863143  0.867331  0.006801
DFS                 0.855451  0.854396  0.843532  0.851126  0.005387
AutoFeat            0.869590  0.859498  0.869030  0.866039  0.004631
OpenFE              0.874918  0.867661  0.856177  0.866252  0.007715
CAAFE               0.874180  0.868014  0.867952  0.870049  0.002922
OCTree              0.857910  0.868681  0.857131  0.861241  0.005271
LLMFE               0.858279  0.881907  0.867703  0.869296  0.009712

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.861926  0.876923  0.863143  0.867331  0.006801
MALMAS(ours)        0.857131  0.867857  0.883789  0.869593  0.010952

In [2]:
import time
set_params(compute_tokens=False)
time.sleep(5000)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Adult_Census_Income

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 00:50:23,601 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:23,604 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:23,605 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:23,605 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:23,606 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:23,606 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:56,573 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:50:59,952 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:51:00,976 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:51:02,409 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:51:05,482 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:51:21,866 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 00:51:30,057 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [temporalfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error localtransform agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 00:51:59,141 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 00:52:09,276 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 00:53:12,972 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 00:53:28,022 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:28,022 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:28,023 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:28,024 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:28,024 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:28,025 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:51,676 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:52,597 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:54,031 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:53:59,459 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:54:00,688 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:54:13,692 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 00:54:28,745 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 00:55:07,555 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Skipping. All newly generated features have been evaluated.
📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 00:55:36,431 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 00:56:16,162 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-28 00:56:31,727 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:31,728 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:31,728 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:31,729 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:31,730 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:31,730 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:55,279 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:56,508 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:56:58,659 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:57:02,140 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 00:57:14,100 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 00:57:33,965 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 00:58:05,811 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 00:58:27,829 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Skipping. All newly generated features have been evaluated.

2025-07-28 00:58:37,659 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 01:00:03,776 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

📝  Generating global conceptual summary...

2025-07-28 01:00:12,392 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 01:00:28,456 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:28,456 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:28,457 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:28,461 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:28,461 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:28,558 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:54,208 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:55,182 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:57,379 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:00:58,973 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 01:01:06,548 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 01:01:28,360 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 01:01:52,013 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Skipping. All newly generated features have been evaluated.

2025-07-28 01:02:03,072 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 01:02:56,525 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 01:03:05,639 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.217261391348309
total_tokens	 111