In [1]:
from data_file.Balance_Scale import Balance_Scale as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *
prompt_path_list = global_config.prompt_path_list

task_name = "Balance_Scale"
task = "classification"

2025-08-04 15:38:41,038 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
        task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.921546  0.900450  0.902498  0.908165  0.009499
DFS           0.997767  0.977033  0.992328  0.989043  0.008778
AutoFeat      0.921546  0.900450  0.902498  0.908165  0.009499
OpenFE        0.921546  0.900450  0.902498  0.908165  0.009499
CAAFE         1.000000  1.000000  1.000000  1.000000  0.000000
OCTree        0.979881  0.991624  0.995765  0.989090  0.006727
LLMFE         1.000000  1.000000  1.000000  1.000000  0.000000

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
        temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0        1         2      mean       std
xgboost_base  0.921546  0.90045  0.902498  0.908165  0.009499
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000

In [5]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
                temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0        1         2      mean       std
xgboost_base  0.921546  0.90045  0.902498  0.908165  0.009499
MALMAS(ours)  0.921546  0.90045  0.902498  0.908165  0.009499
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000

In [6]:
baseline_summary_auc = run_baseline_experiments(
        task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.921546  0.900450  0.902498  0.908165  0.009499
DFS           0.997767  0.977033  0.992328  0.989043  0.008778
AutoFeat      0.921546  0.900450  0.902498  0.908165  0.009499
OpenFE        0.921546  0.900450  0.902498  0.908165  0.009499
CAAFE         1.000000  1.000000  1.000000  1.000000  0.000000
OCTree        0.966132  0.941172  0.890883  0.932729  0.031295
LLMFE         0.982826  1.000000  1.000000  0.994275  0.008096

In [7]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
        temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0        1         2      mean       std
xgboost_base  0.921546  0.90045  0.902498  0.908165  0.009499
MALMAS(ours)  1.000000  1.00000  1.000000  1.000000  0.000000

In [8]:
baseline_summary_acc = run_baseline_experiments(
        task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                  0      1      2      mean       std
xgboost_base  0.860  0.848  0.840  0.849333  0.008219
DFS           0.964  0.956  0.964  0.961333  0.003771
AutoFeat      0.860  0.848  0.840  0.849333  0.008219
OpenFE        0.860  0.848  0.840  0.849333  0.008219
CAAFE         1.000  1.000  1.000  1.000000  0.000000
OCTree        0.884  0.880  0.840  0.868000  0.019866
LLMFE         0.960  1.000  1.000  0.986667  0.018856

In [9]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
        temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                 0      1     2      mean       std
xgboost_base  0.86  0.848  0.84  0.849333  0.008219
MALMAS(ours)  1.00  1.000  1.00  1.000000  0.000000

In [10]:
baseline_summary_auc_m = run_baseline_experiments(
        task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.928650  0.909979  0.913606  0.917412  0.008084
DFS            0.997606  0.982885  0.990931  0.990474  0.006019
AutoFeat       0.929286  0.912681  0.912775  0.918247  0.007805
OpenFE         0.928650  0.909979  0.913606  0.917412  0.008084
CAAFE          1.000000  1.000000  1.000000  1.000000  0.000000
OCTree         0.983826  0.945810  0.880269  0.936635  0.042772
LLMFE          0.980026  1.000000  1.000000  0.993342  0.009416

In [11]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
        temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
lightgbm_base  0.92865  0.909979  0.913606  0.917412  0.008084
MALMAS(ours)   1.00000  1.000000  1.000000  1.000000  0.000000

In [12]:
baseline_summary_auc_c = run_baseline_experiments(
        task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.946134  0.927835  0.939304  0.937758  0.007550
DFS            0.999057  0.982527  0.993947  0.991843  0.006910
AutoFeat       0.943394  0.929415  0.935647  0.936152  0.005718
OpenFE         0.943990  0.928854  0.938405  0.937083  0.006249
CAAFE          1.000000  1.000000  1.000000  1.000000  0.000000
OCTree         0.977713  0.944857  0.918877  0.947149  0.024074
LLMFE          0.980529  1.000000  1.000000  0.993510  0.009179

In [13]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
        temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean      std
mlp_base  0.946134  0.927835  0.939304  0.937758  0.00755
MALMAS(ours)   1.000000  1.000000  1.000000  1.000000  0.00000

In [14]:
baseline_summary_auc_r = run_baseline_experiments(
        task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.821885  0.838403  0.825377  0.828555  0.007108
DFS                 0.990843  0.957692  0.965965  0.971500  0.014089
AutoFeat            0.844892  0.845214  0.840039  0.843382  0.002367
OpenFE              0.840958  0.842037  0.826577  0.836524  0.007048
CAAFE               1.000000  1.000000  1.000000  1.000000  0.000000
OCTree              0.932570  0.860347  0.818818  0.870578  0.046999
LLMFE               0.946966  1.000000  1.000000  0.982322  0.025001

In [15]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
        temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.821885  0.838403  0.825377  0.828555  0.007108
MALMAS(ours)        1.000000  1.000000  1.000000  1.000000  0.000000

In [2]:
import time
set_params(compute_tokens=False)
time.sleep(3600*7)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Balance_Scale

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 06:29:24,178 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:24,181 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:24,182 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:24,182 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:24,183 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:24,183 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:38,924 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:39,435 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:29:44,659 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 06:30:00,430 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:30:00,431 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:30:06,981 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 06:30:12,103 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:30:20,498 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...
[❌code error localpattern agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 06:30:29,203 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 06:30:42,467 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 06:31:06,170 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 06:31:25,419 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:31:34,226 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

🔁  ===== The 2-th round =====

2025-07-28 06:31:45,595 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:31:45,596 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:31:45,596 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:31:45,597 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:31:45,597 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:31:45,697 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:32:04,690 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:32:07,864 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:32:08,839 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:32:09,813 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:32:11,499 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:32:13,856 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [localtransform] Generating local conceptual summary ...

2025-07-28 06:32:31,163 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 06:32:40,888 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 06:32:55,994 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:03,728 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.
⚠️ [aggregationconstruct]Skipping. All newly generated features have been evaluated.

📝  Generating global conceptual summary...

🔁  ===== The 3-th round =====

2025-07-28 06:33:14,784 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:14,785 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:14,785 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:14,785 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:14,786 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:14,786 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:31,833 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:33,933 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:34,138 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:36,239 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:39,051 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:33:43,715 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 06:33:55,692 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 06:34:06,600 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [localtransform] Generating local conceptual summary ...

2025-07-28 06:34:28,153 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Skipping. All newly generated features have been evaluated.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 06:34:37,728 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 06:34:45,229 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 06:34:57,184 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:34:57,185 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:34:57,185 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:34:57,186 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:34:57,187 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:34:57,187 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:35:13,007 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:35:13,773 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:35:15,514 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:35:18,074 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:35:18,224 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 06:35:19,609 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 06:35:32,410 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 06:35:47,616 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 06:35:59,853 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.
📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 06:36:19,668 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 06:36:28,729 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.12184083342552185
total_tokens	 88