In [1]:
from data_file.Bank_Marketing import Bank_Marketing as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *
prompt_path_list = global_config.prompt_path_list

task_name = "Bank_Marketing"
task = "classification"

2025-08-04 15:39:34,462 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.868086  0.861028  0.878491  0.869202  0.007173
DFS           0.892483  0.873099  0.907569  0.891050  0.014109
AutoFeat      0.868086  0.861028  0.878491  0.869202  0.007173
OpenFE        0.906945  0.905175  0.898934  0.903685  0.003436
CAAFE         0.882947  0.861028  0.876289  0.873421  0.009175
OCTree        0.868086  0.861028  0.878491  0.869202  0.007173
LLMFE         0.868086  0.854415  0.878491  0.866998  0.009859

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.868086  0.861028  0.878491  0.869202  0.007173
MALMAS(ours)  0.880324  0.874008  0.900256  0.884863  0.011186

In [5]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.868086  0.861028  0.878491  0.869202  0.007173
MALMAS(ours)  0.901462  0.846644  0.886950  0.878352  0.023191
MALMAS(ours)  0.876907  0.871032  0.886069  0.878003  0.006188
MALMAS(ours)  0.884218  0.869544  0.879108  0.877623  0.006082
MALMAS(ours)  0.898919  0.872851  0.891620  0.887797  0.010981
MALMAS(ours)  0.880006  0.876405  0.885541  0.880651  0.003757
MALMAS(ours)  0.893516  0.868469  0.890211  0.884065  0.011110

In [6]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.868086  0.861028  0.878491  0.869202  0.007173
DFS           0.892483  0.873099  0.907569  0.891050  0.014109
AutoFeat      0.868086  0.861028  0.878491  0.869202  0.007173
OpenFE        0.906945  0.905175  0.898934  0.903685  0.003436
CAAFE         0.876828  0.845651  0.898317  0.873599  0.021622
OCTree        0.883106  0.859788  0.875848  0.872914  0.009743
LLMFE         0.873093  0.860780  0.890299  0.874724  0.012106

In [7]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.868086  0.861028  0.878491  0.869202  0.007173
MALMAS(ours)  0.897409  0.892692  0.895938  0.895346  0.001971

In [8]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.860606  0.875758  0.881818  0.872727  0.008921
DFS           0.878788  0.884848  0.896970  0.886869  0.007559
AutoFeat      0.860606  0.875758  0.881818  0.872727  0.008921
OpenFE        0.884848  0.881818  0.884848  0.883838  0.001428
CAAFE         0.857576  0.866667  0.881818  0.868687  0.009999
OCTree        0.860606  0.875758  0.906061  0.880808  0.018897
LLMFE         0.857576  0.866667  0.878788  0.867677  0.008689

In [9]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.860606  0.875758  0.881818  0.872727  0.008921
MALMAS(ours)  0.887879  0.896970  0.906061  0.896970  0.007423

In [10]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.885966  0.867146  0.882192  0.878435  0.008130
DFS            0.898999  0.878472  0.911005  0.896159  0.013433
AutoFeat       0.887873  0.867146  0.882192  0.879071  0.008745
OpenFE         0.905753  0.891038  0.903251  0.900014  0.006429
CAAFE          0.888112  0.856812  0.901753  0.882226  0.018813
OCTree         0.884139  0.872189  0.888448  0.881592  0.006878
LLMFE          0.877861  0.854167  0.877963  0.869997  0.011194

In [11]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.885966  0.867146  0.882192  0.878435  0.008130
MALMAS(ours)   0.894946  0.900132  0.912151  0.902410  0.007206

In [12]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.903449  0.884590  0.911534  0.899858  0.011289
DFS            0.916481  0.891452  0.919288  0.909074  0.012513
AutoFeat       0.907581  0.888062  0.911534  0.902392  0.010261
OpenFE         0.920137  0.903274  0.925897  0.916436  0.009599
CAAFE          0.909091  0.881944  0.915587  0.902208  0.014572
OCTree         0.890099  0.880456  0.898934  0.889830  0.007546
LLMFE          0.909011  0.884921  0.910212  0.901381  0.011650

In [13]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.903449  0.884590  0.911534  0.899858  0.011289
MALMAS(ours)   0.920852  0.909061  0.914970  0.914961  0.004814

In [14]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.883900  0.892857  0.897128  0.891295  0.005512
DFS                 0.908813  0.884879  0.908494  0.900729  0.011208
AutoFeat            0.885013  0.889964  0.897128  0.890701  0.004973
OpenFE              0.910084  0.898272  0.916204  0.908187  0.007443
CAAFE               0.892999  0.905299  0.895850  0.898049  0.005257
OCTree              0.896893  0.868552  0.890651  0.885365  0.012159
LLMFE               0.870272  0.881738  0.887567  0.879859  0.007185

In [15]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                          0         1         2      mean       std
random_forest_base  0.88390  0.892857  0.897128  0.891295  0.005512
MALMAS(ours)        0.91664  0.903067  0.899154  0.906287  0.007493

In [2]:
import time
set_params(compute_tokens=False)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Bank_Marketing

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 04:28:15,943 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:15,945 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:15,946 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:15,946 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:15,947 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:15,956 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:41,851 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:51,374 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:53,216 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:28:58,951 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] could not convert string to float: 'nov'

2025-07-28 04:29:00,591 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:29:04,890 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:29:09,102 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 04:29:24,906 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 04:29:51,586 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [localpattern]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error unaryfeature agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 04:30:33,059 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 04:31:37,671 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 04:31:46,583 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 04:31:58,460 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:31:58,461 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:31:58,461 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:31:58,462 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:31:58,462 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:31:58,462 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:32:17,199 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:32:20,270 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:32:24,162 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:32:24,168 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:32:38,291 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] unsupported operand type(s) for -: 'str' and 'int'

2025-07-28 04:32:41,570 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 04:32:51,808 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 04:33:11,368 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 04:33:26,523 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:33:36,148 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 04:33:52,533 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [localpattern]Skipping. All newly generated features have been evaluated.

📝  Generating global conceptual summary...

2025-07-28 04:34:12,601 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-28 04:34:26,325 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:26,326 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:26,329 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:26,335 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:26,335 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:26,427 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:44,039 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:47,672 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:52,028 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:52,539 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:34:57,864 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 04:35:08,104 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Skipping. All newly generated features have been evaluated.

2025-07-28 04:35:16,602 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 04:35:27,355 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] unsupported operand type(s) for -: 'str' and 'int'

2025-07-28 04:35:35,854 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 04:36:05,345 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 04:36:32,173 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 04:36:44,158 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:36:44,159 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:36:44,162 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:36:44,165 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:36:44,165 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:36:44,257 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:37:05,863 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:37:07,810 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:37:07,911 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:37:09,447 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:37:13,236 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:37:16,104 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] can't multiply sequence by non-int of type 'float'

2025-07-28 04:37:26,445 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 04:37:40,066 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 04:37:50,965 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 04:38:05,665 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 04:38:27,681 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Skipping. All newly generated features have been evaluated.
[❌code error temporalfeature agent] could not convert string to float: 'nov'

2025-07-28 04:38:38,432 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] could not convert string to float: 'fri'

2025-07-28 04:39:04,750 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:39:29,837 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] can't multiply sequence by non-int of type 'float'

2025-07-28 04:39:51,346 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] could not convert string to float: 'nov'

2025-07-28 04:40:13,255 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 04:40:49,041 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 04:40:56,263 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...
total_times	 0.21565239661269717
total_tokens	 141

In [3]:
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

total_times	 0.21565239661269717
total_tokens	 141