In [1]:
from data_file.Banknote_Authentication import Banknote_Authentication as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *

prompt_path_list = global_config.prompt_path_list
task_name = "Banknote_Authentication"
task = "classification"

2025-08-04 15:41:05,586 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.995626  0.996505  0.991809  0.994647  0.002038
DFS           0.997438  0.998752  0.996508  0.997566  0.000921
AutoFeat      0.995814  0.996391  0.990777  0.994327  0.002522
OpenFE        0.996780  0.999182  0.999403  0.998455  0.001188
CAAFE         0.995875  0.996706  0.988163  0.993581  0.003847
OCTree        0.987215  0.996505  0.993605  0.992442  0.003881
LLMFE         0.985933  0.996223  0.994799  0.992318  0.004552

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.995626  0.996505  0.991809  0.994647  0.002038
MALMAS(ours)  0.999302  0.998424  0.999893  0.999206  0.000604

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.995626  0.996505  0.991809  0.994647  0.002038
MALMAS(ours)  0.995519  0.987402  0.992412  0.991778  0.003344
MALMAS(ours)  0.997035  0.999960  0.989322  0.995439  0.004487
MALMAS(ours)  0.999873  0.992514  1.000000  0.997462  0.003499
MALMAS(ours)  0.999832  0.998886  1.000000  0.999573  0.000490
MALMAS(ours)  1.000000  0.999007  1.000000  0.999669  0.000468
MALMAS(ours)  0.999826  0.999879  1.000000  0.999902  0.000073

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.995626  0.996505  0.991809  0.994647  0.002038
DFS           0.997438  0.998752  0.996508  0.997566  0.000921
AutoFeat      0.995814  0.996391  0.990777  0.994327  0.002522
OpenFE        0.996780  0.999182  0.999403  0.998455  0.001188
CAAFE         0.995626  0.991836  0.990274  0.992579  0.002247
OCTree        0.995626  0.996505  0.986728  0.992953  0.004416
LLMFE         0.989690  0.989764  0.993418  0.990957  0.001740

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.995626  0.996505  0.991809  0.994647  0.002038
MALMAS(ours)  1.000000  0.997914  0.999450  0.999121  0.000883

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.978142  0.974499  0.981785  0.978142  0.002974
DFS           0.976321  0.983607  0.972678  0.977535  0.004544
AutoFeat      0.979964  0.976321  0.978142  0.978142  0.001487
OpenFE        0.989071  0.987250  0.996357  0.990893  0.003935
CAAFE         0.978142  0.978142  0.978142  0.978142  0.000000
OCTree        0.978142  0.974499  0.965392  0.972678  0.005362
LLMFE         0.978142  0.985428  0.985428  0.982999  0.003435

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.978142  0.974499  0.981785  0.978142  0.002974
MALMAS(ours)  1.000000  0.994536  0.985428  0.993321  0.006011

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.993674  0.996109  0.996206  0.995330  0.001171
DFS            0.999718  0.998806  0.995006  0.997844  0.002040
AutoFeat       0.996217  0.996190  0.996179  0.996195  0.000016
OpenFE         0.998632  0.998209  0.999571  0.998804  0.000569
CAAFE          0.993426  0.995814  0.995938  0.995059  0.001156
OCTree         0.993674  0.996109  0.994316  0.994700  0.001030
LLMFE          0.991414  0.995123  0.995630  0.994056  0.001879

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2     mean       std
lightgbm_base  0.993674  0.996109  0.996206  0.99533  0.001171
MALMAS(ours)   1.000000  0.999638  0.998713  0.99945  0.000542

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean           std
mlp_base  1.000000  0.999920  1.000000  0.999973  3.794611e-05
DFS            0.999920  1.000000  1.000000  0.999973  3.794611e-05
AutoFeat       1.000000  0.999893  0.999960  0.999951  4.427250e-05
OpenFE         1.000000  1.000000  1.000000  1.000000  6.409876e-17
CAAFE          0.999973  0.999812  0.999987  0.999924  7.924655e-05
OCTree         1.000000  0.999920  0.999826  0.999915  7.121706e-05
LLMFE          0.999852  0.999262  1.000000  0.999705  3.188000e-04

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                 0         1    2      mean       std
mlp_base  1.0  0.999920  1.0  0.999973  0.000038
MALMAS(ours)   1.0  0.999987  1.0  0.999996  0.000006

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.999973  0.999604  0.999973  0.999850  0.000174
DFS                 1.000000  0.999973  1.000000  0.999991  0.000013
AutoFeat            0.999960  0.999416  0.999940  0.999772  0.000252
OpenFE              1.000000  0.999940  1.000000  0.999980  0.000028
CAAFE               1.000000  0.999832  0.999873  0.999902  0.000071
OCTree              0.999973  0.999604  0.999605  0.999727  0.000174
LLMFE               0.999893  0.999846  1.000000  0.999913  0.000065

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2     mean       std
random_forest_base  0.999973  0.999604  0.999973  0.99985  0.000174
MALMAS(ours)        1.000000  1.000000  1.000000  1.00000  0.000000

In [2]:
import time
set_params(compute_tokens=False)
time.sleep(3600*8)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Banknote_Authentication

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 07:29:43,707 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:29:43,709 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:29:43,710 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:29:43,710 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:29:43,711 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:29:43,730 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:29:56,864 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:02,036 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:02,500 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:04,801 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:06,690 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:08,335 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 07:30:14,428 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:15,395 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...
📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 07:30:25,128 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 07:30:35,369 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 07:30:47,651 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:30:54,977 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

🔁  ===== The 2-th round =====

2025-07-28 07:31:08,084 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:08,084 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:08,084 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:08,085 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:08,086 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:08,086 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:20,936 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:22,113 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:23,342 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:26,465 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:30,564 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:31,124 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:33,939 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...
📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 07:31:41,058 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:31:49,298 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...
⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 07:32:01,434 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:09,882 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

📝  Generating global conceptual summary...

2025-07-28 07:32:15,410 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-28 07:32:25,908 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:25,909 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:25,909 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:25,910 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:25,910 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:25,911 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:39,885 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:40,091 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:41,985 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:32:48,641 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 07:32:51,815 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 07:33:01,543 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:33:06,513 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:33:06,564 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:33:08,760 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 07:33:19,156 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 07:33:26,120 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 07:33:45,370 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 07:33:53,043 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 07:34:02,165 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:02,166 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:02,166 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:02,167 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:02,167 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:02,168 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:14,658 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:15,983 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:20,442 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:22,844 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:24,790 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:26,735 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...
📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 07:34:34,675 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:41,788 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:34:42,765 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 07:34:53,462 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error aggregationconstruct agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 07:35:00,835 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error aggregationconstruct agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 07:35:15,888 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error aggregationconstruct agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 07:35:30,632 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 07:35:48,197 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 07:36:05,756 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 07:36:12,924 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.11133049892054664
total_tokens	 93