In [1]:
from data_file.Car_Evaluation import Car_Evaluation as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *

prompt_path_list = global_config.prompt_path_list
task_name = "Car_Evaluation"
task = "classification"

2025-08-04 15:42:29,518 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.977073  0.982448  0.985720  0.981747  0.003565
DFS           0.975567  0.978814  0.980725  0.978369  0.002129
AutoFeat      0.977073  0.982448  0.985720  0.981747  0.003565
OpenFE        0.987680  0.995793  0.998097  0.993857  0.004468
CAAFE         0.991316  0.993000  0.995290  0.993202  0.001628
OCTree        0.977073  0.978976  0.991805  0.982618  0.006542
LLMFE         0.990114  0.991713  0.991456  0.991094  0.000701

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.977073  0.982448  0.985720  0.981747  0.003565
MALMAS(ours)  0.998825  0.999434  0.997502  0.998587  0.000807

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.977073  0.982448  0.985720  0.981747  0.003565
MALMAS(ours)  0.990825  0.989188  0.992173  0.990729  0.001220
MALMAS(ours)  0.996128  0.995506  0.997172  0.996269  0.000687
MALMAS(ours)  0.996880  0.997940  0.998613  0.997811  0.000713
MALMAS(ours)  0.995270  0.992564  0.996651  0.994828  0.001697
MALMAS(ours)  0.995351  0.996327  0.999726  0.997135  0.001875
MALMAS(ours)  0.997401  0.999355  0.999182  0.998646  0.000883

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.977073  0.982448  0.985720  0.981747  0.003565
DFS           0.975567  0.978814  0.980725  0.978369  0.002129
AutoFeat      0.977073  0.982448  0.985720  0.981747  0.003565
OpenFE        0.987680  0.995793  0.998097  0.993857  0.004468
CAAFE         0.989629  0.980291  0.993867  0.987929  0.005671
OCTree        0.977073  0.982448  0.966534  0.975352  0.006610
LLMFE         0.983590  0.984260  0.991456  0.986436  0.003561

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.977073  0.982448  0.985720  0.981747  0.003565
MALMAS(ours)  0.999581  0.998860  0.999606  0.999349  0.000346

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.902893  0.896694  0.902893  0.900826  0.002922
DFS           0.911157  0.913223  0.925620  0.916667  0.006387
AutoFeat      0.902893  0.896694  0.902893  0.900826  0.002922
OpenFE        0.948347  0.956612  0.977273  0.960744  0.012165
CAAFE         0.940083  0.896694  0.933884  0.923554  0.019160
OCTree        0.902893  0.896694  0.896694  0.898760  0.002922
LLMFE         0.915289  0.894628  0.938017  0.915978  0.017720

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.902893  0.896694  0.902893  0.900826  0.002922
MALMAS(ours)  0.991736  0.985537  0.989669  0.988981  0.002577

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.978073  0.981423  0.984869  0.981455  0.002775
DFS            0.986885  0.990696  0.988450  0.988677  0.001564
AutoFeat       0.978073  0.981423  0.984869  0.981455  0.002775
OpenFE         0.996833  0.998775  0.996193  0.997267  0.001098
CAAFE          0.990603  0.983840  0.992308  0.988917  0.003657
OCTree         0.978073  0.981423  0.979528  0.979675  0.001372
LLMFE          0.984188  0.981384  0.991913  0.985828  0.004452

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.978073  0.981423  0.984869  0.981455  0.002775
MALMAS(ours)   0.998005  0.999126  0.998562  0.998564  0.000458

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.998280  0.997222  0.997710  0.997737  0.000432
DFS            0.992742  0.994102  0.996102  0.994315  0.001380
AutoFeat       0.998280  0.997222  0.997710  0.997737  0.000432
OpenFE         0.999218  0.999279  0.998879  0.999125  0.000176
CAAFE          0.997276  0.997726  0.998122  0.997708  0.000346
OCTree         0.998280  0.997222  0.993529  0.996344  0.002036
LLMFE          0.997745  0.997207  0.997531  0.997494  0.000221

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.998280  0.997222  0.997710  0.997737  0.000432
MALMAS(ours)   0.999306  0.999759  0.999768  0.999611  0.000215

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.991318  0.993616  0.993648  0.992860  0.001091
DFS                 0.987263  0.991696  0.988288  0.989082  0.001895
AutoFeat            0.991318  0.993616  0.993648  0.992860  0.001091
OpenFE              0.996116  0.998695  0.996885  0.997232  0.001081
CAAFE               0.992243  0.987287  0.995873  0.991801  0.003519
OCTree              0.991318  0.993616  0.985530  0.990154  0.003402
LLMFE               0.995741  0.994601  0.996505  0.995616  0.000783

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.991318  0.993616  0.993648  0.992860  0.001091
MALMAS(ours)        0.999556  0.999422  0.999038  0.999339  0.000219

In [2]:
import time
set_params(compute_tokens=False)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Car_Evaluation

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 09:15:59,320 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:15:59,323 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:15:59,323 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:15:59,323 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:15:59,324 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:15:59,324 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:16:22,051 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:16:23,280 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:16:23,382 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:16:24,099 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:16:27,171 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:16:32,291 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 09:16:44,376 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 09:16:55,229 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error aggregationconstruct agent] Cannot perform 'rand_' with a dtyped [bool] array

2025-07-28 09:17:04,241 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 09:17:07,056 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 09:17:21,546 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 09:17:32,298 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 09:17:42,333 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:42,334 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:42,334 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:42,335 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:42,336 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:42,336 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:58,255 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:17:59,385 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:18:00,151 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:18:03,837 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:18:05,680 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 09:18:08,753 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:18:17,764 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 09:18:20,890 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 09:18:32,304 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 09:18:42,391 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:18:50,634 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error aggregationconstruct agent] could not convert string to float: 'more'
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 09:18:55,290 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Skipping. All newly generated features have been evaluated.

📝  Generating global conceptual summary...

2025-07-28 09:19:20,534 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-28 09:19:30,567 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:30,568 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:30,568 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:30,569 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:30,569 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:30,577 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:45,008 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:50,385 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:52,380 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:52,893 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:19:56,018 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:20:00,163 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 09:20:07,280 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 09:20:12,259 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 09:20:23,660 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 09:20:34,883 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 09:20:46,039 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 09:20:53,564 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 09:21:04,062 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:04,062 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:04,063 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:04,063 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:04,064 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:04,064 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:24,438 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:24,438 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:25,617 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:26,230 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:28,793 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:28,996 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:21:44,918 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...
📝 [localtransform] Generating local conceptual summary ...

2025-07-28 09:21:56,080 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:22:04,172 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error temporalfeature agent] 'numpy.ndarray' object has no attribute 'pct_chang
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 09:22:07,447 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 09:22:18,710 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...
⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.
📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 09:22:28,848 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 09:22:37,961 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.11464809954166412
total_tokens	 97

In [3]:
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

total_times	 0.11464809954166412
total_tokens	 97