In [1]:
from data_file.Telco_Customer_Churn import Telco_Customer_Churn as read_data 
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *

prompt_path_list = global_config.prompt_path_list
task_name = "Telco_Customer_Churn"
task = "classification"

2025-08-04 15:43:04,139 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.827607  0.831507  0.827017  0.828710  0.001992
DFS           0.831699  0.836278  0.830106  0.832694  0.002616
AutoFeat      0.827607  0.831507  0.827017  0.828710  0.001992
OpenFE        0.827042  0.828527  0.827398  0.827656  0.000633
CAAFE         0.827051  0.832657  0.831160  0.830290  0.002370
OCTree        0.829852  0.827828  0.824303  0.827328  0.002293
LLMFE         0.827544  0.833678  0.829458  0.830226  0.002562

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2     mean       std
xgboost_base  0.827607  0.831507  0.827017  0.82871  0.001992
MALMAS(ours)  0.833947  0.835648  0.831594  0.83373  0.001662

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.827607  0.831507  0.827017  0.828710  0.001992
MALMAS(ours)  0.833570  0.833806  0.831166  0.832847  0.001193
MALMAS(ours)  0.833421  0.834034  0.831691  0.833048  0.000992
MALMAS(ours)  0.832869  0.832530  0.827281  0.830893  0.002558
MALMAS(ours)  0.828728  0.812136  0.833324  0.824729  0.009100
MALMAS(ours)  0.833275  0.833140  0.831370  0.832595  0.000868
MALMAS(ours)  0.835894  0.818418  0.830917  0.828410  0.007351

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.827607  0.831507  0.827017  0.828710  0.001992
DFS           0.831699  0.836278  0.830106  0.832694  0.002616
AutoFeat      0.827607  0.831507  0.827017  0.828710  0.001992
OpenFE        0.827042  0.828527  0.827398  0.827656  0.000633
CAAFE         0.830142  0.823055  0.828467  0.827221  0.003024
OCTree        0.826281  0.825562  0.822201  0.824681  0.001778
LLMFE         0.829895  0.829448  0.826724  0.828689  0.001402

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.827607  0.831507  0.827017  0.828710  0.001992
MALMAS(ours)  0.834255  0.836081  0.834355  0.834897  0.000838

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.785283  0.788127  0.788482  0.787297  0.001432
DFS           0.788838  0.793459  0.793459  0.791918  0.002179
AutoFeat      0.785283  0.788127  0.788482  0.787297  0.001432
OpenFE        0.784927  0.784927  0.792037  0.787297  0.003352
CAAFE         0.780661  0.785994  0.786349  0.784335  0.002602
OCTree        0.791326  0.786705  0.789904  0.789312  0.001933
LLMFE         0.785638  0.785638  0.789549  0.786942  0.001843

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.785283  0.788127  0.788482  0.787297  0.001432
MALMAS(ours)  0.785638  0.796303  0.791326  0.791089  0.004357

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.826336  0.831134  0.827409  0.828293  0.002056
DFS            0.826790  0.830031  0.827496  0.828106  0.001392
AutoFeat       0.825848  0.828870  0.827409  0.827376  0.001234
OpenFE         0.827864  0.825439  0.829119  0.827474  0.001528
CAAFE          0.826330  0.817399  0.827166  0.823632  0.004420
OCTree         0.827155  0.825084  0.822462  0.824900  0.001920
LLMFE          0.826885  0.826655  0.826027  0.826522  0.000363

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.826336  0.831134  0.827409  0.828293  0.002056
MALMAS(ours)   0.826069  0.829926  0.829392  0.828463  0.001706

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.832122  0.839943  0.836518  0.836194  0.003201
DFS            0.838771  0.836882  0.835271  0.836975  0.001430
AutoFeat       0.834984  0.838433  0.838901  0.837439  0.001746
OpenFE         0.833657  0.834485  0.834286  0.834143  0.000353
CAAFE          0.833855  0.831018  0.831913  0.832262  0.001184
OCTree         0.835323  0.836181  0.832928  0.834810  0.001376
LLMFE          0.835180  0.838111  0.836538  0.836610  0.001198

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.832122  0.839943  0.836518  0.836194  0.003201
MALMAS(ours)   0.833858  0.839828  0.837140  0.836942  0.002441

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.819804  0.818774  0.817105  0.818561  0.001112
DFS                 0.806927  0.810460  0.811403  0.809597  0.001927
AutoFeat            0.819730  0.822621  0.820362  0.820904  0.001241
OpenFE              0.817730  0.817313  0.817834  0.817626  0.000225
CAAFE               0.810625  0.804464  0.813660  0.809583  0.003826
OCTree              0.818582  0.820136  0.819644  0.819454  0.000649
LLMFE               0.822268  0.819305  0.822542  0.821371  0.001465

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.819804  0.818774  0.817105  0.818561  0.001112
MALMAS(ours)        0.818865  0.823266  0.819645  0.820592  0.001917

In [3]:
import time
set_params(compute_tokens=False)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Telco_Customer_Churn

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 10:38:14,481 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:14,483 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:14,484 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:14,484 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:14,485 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:14,580 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:46,136 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:50,829 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:51,753 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:54,823 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:38:56,921 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:39:04,142 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 10:39:26,315 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [localtransform]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 10:40:24,679 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error localpattern agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:40:36,000 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 10:40:55,452 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error localpattern agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:41:35,432 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 10:42:57,103 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 10:43:08,060 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 10:43:23,420 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:23,421 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:23,422 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:23,422 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:23,423 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:23,423 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:48,355 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:49,483 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:50,350 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:50,351 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:43:56,086 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:44:01,512 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 10:44:27,010 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 10:44:50,203 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:45:20,104 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:45:46,574 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 10:46:15,963 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:46:24,770 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 10:47:17,197 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 10:47:27,437 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-28 10:47:44,539 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:47:44,554 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:47:44,556 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:47:44,560 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:47:44,642 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:47:44,643 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:48:09,680 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:48:17,748 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:48:19,712 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:48:21,252 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:48:45,413 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:48:55,502 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:48:55,503 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 10:49:14,549 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 10:49:51,307 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:50:24,995 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 10:51:03,241 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 10:51:50,191 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 10:51:59,408 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 10:52:14,869 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:14,870 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:14,870 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:14,871 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:14,871 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:14,896 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:39,502 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:41,086 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:41,289 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:44,987 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:52:45,077 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 10:53:19,231 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:53:48,874 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 10:54:19,491 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:54:40,892 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:54:51,337 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 10:55:03,643 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:55:34,857 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:56:17,256 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:56:59,849 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:57:39,481 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 10:58:59,451 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 10:59:10,306 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.35564974281522965
total_tokens	 142