In [1]:
from data_file.Heart_Disease import Heart_Disease as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *

prompt_path_list = global_config.prompt_path_list
task_name = "Heart_Disease"
task = "classification"

2025-08-04 15:44:16,450 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.915038  0.912751  0.915770  0.914520  0.001286
DFS           0.907706  0.914126  0.926680  0.916171  0.007880
AutoFeat      0.915038  0.913170  0.913020  0.913743  0.000918
OpenFE        0.924884  0.908925  0.926710  0.920173  0.007988
CAAFE         0.912375  0.907311  0.916577  0.912088  0.003788
OCTree        0.914948  0.907012  0.913140  0.911700  0.003396
LLMFE         0.913841  0.907311  0.917982  0.913045  0.004393

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.915038  0.912751  0.915770  0.914520  0.001286
MALMAS(ours)  0.912943  0.909314  0.916547  0.912935  0.002953

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.915038  0.912751  0.915770  0.914520  0.001286
MALMAS(ours)  0.915038  0.913857  0.915770  0.914888  0.000788
MALMAS(ours)  0.912016  0.910450  0.906145  0.909537  0.002482
MALMAS(ours)  0.908365  0.896341  0.919805  0.908170  0.009580
MALMAS(ours)  0.918091  0.897029  0.917235  0.910785  0.009733
MALMAS(ours)  0.917612  0.902379  0.919596  0.913196  0.007691
MALMAS(ours)  0.898489  0.904113  0.918520  0.907040  0.008436

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.915038  0.912751  0.915770  0.914520  0.001286
DFS           0.907706  0.914126  0.926680  0.916171  0.007880
AutoFeat      0.915038  0.913170  0.913020  0.913743  0.000918
OpenFE        0.924884  0.908925  0.926710  0.920173  0.007988
CAAFE         0.911956  0.907311  0.906534  0.908600  0.002394
OCTree        0.912045  0.904023  0.921330  0.912466  0.007072
LLMFE         0.916415  0.906683  0.909822  0.910973  0.004055

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.915038  0.912751  0.915770  0.914520  0.001286
MALMAS(ours)  0.923537  0.920791  0.923213  0.922514  0.001225

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.842391  0.864130  0.823370  0.843297  0.016653
DFS           0.836957  0.847826  0.836957  0.840580  0.005124
AutoFeat      0.842391  0.855978  0.831522  0.843297  0.010005
OpenFE        0.858696  0.853261  0.861413  0.857790  0.003389
CAAFE         0.839674  0.839674  0.812500  0.830616  0.012810
OCTree        0.853261  0.839674  0.864130  0.852355  0.010005
LLMFE         0.839674  0.845109  0.839674  0.841486  0.002562

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0        1         2      mean       std
xgboost_base  0.842391  0.86413  0.823370  0.843297  0.016653
MALMAS(ours)  0.858696  0.86413  0.869565  0.864130  0.004437

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.919348  0.912990  0.919446  0.917261  0.003020
DFS            0.908424  0.916159  0.927875  0.917486  0.007996
AutoFeat       0.919348  0.911167  0.919686  0.916733  0.003938
OpenFE         0.927398  0.910748  0.927427  0.921858  0.007856
CAAFE          0.916924  0.908596  0.911496  0.912339  0.003451
OCTree         0.916894  0.908387  0.930924  0.918735  0.009292
LLMFE          0.914200  0.911675  0.917205  0.914360  0.002260

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0        1         2      mean       std
lightgbm_base  0.919348  0.91299  0.919446  0.917261  0.003020
MALMAS(ours)   0.920874  0.91568  0.923990  0.920181  0.003427

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.931378  0.919745  0.938905  0.930009  0.007881
DFS            0.928356  0.915292  0.935796  0.926481  0.008475
AutoFeat       0.932037  0.918550  0.938187  0.929591  0.008201
OpenFE         0.933443  0.919267  0.938397  0.930369  0.008107
CAAFE          0.930450  0.916966  0.937679  0.928365  0.008584
OCTree         0.927009  0.911346  0.941416  0.926590  0.012279
LLMFE          0.932276  0.916697  0.937410  0.928794  0.008807

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.931378  0.919745  0.938905  0.930009  0.007881
MALMAS(ours)   0.926680  0.919984  0.937321  0.927995  0.007138

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.918824  0.912736  0.926336  0.919299  0.005562
DFS                 0.914634  0.909657  0.922675  0.915655  0.005363
AutoFeat            0.921457  0.916816  0.931552  0.923275  0.006152
OpenFE              0.921098  0.914036  0.929265  0.921467  0.006223
CAAFE               0.917941  0.913573  0.918071  0.916529  0.002091
OCTree              0.924929  0.913409  0.930909  0.923082  0.007263
LLMFE               0.915382  0.914350  0.918475  0.916069  0.001753

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.918824  0.912736  0.926336  0.919299  0.005562
MALMAS(ours)        0.917148  0.914813  0.924961  0.918974  0.004339

In [2]:
import time
set_params(compute_tokens=False)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Heart_Disease

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-27 22:34:08,427 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:08,429 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:08,430 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:08,431 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:08,431 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:08,431 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:39,351 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:42,218 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:34:42,369 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-27 22:35:03,724 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:35:04,541 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:35:07,054 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [aggregationconstruct]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-27 22:35:51,645 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error localtransform agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-27 22:36:06,496 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-27 22:36:47,965 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-27 22:36:57,849 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-27 22:37:12,336 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:12,337 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:12,337 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:12,337 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:12,338 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:12,338 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:31,383 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:36,093 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:39,370 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:40,496 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:51,248 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:37:52,327 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-27 22:38:05,025 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-27 22:38:32,055 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-27 22:38:58,629 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-27 22:39:17,215 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-27 22:39:30,382 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-27 22:39:48,291 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:39:48,292 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:39:48,292 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:39:48,292 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:39:48,293 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:39:48,293 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:40:13,639 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:40:14,917 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:40:24,184 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:40:24,798 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:40:26,896 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:40:28,535 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [aggregationconstruct]Skipping. All newly generated features have been evaluated.
⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [localtransform] Generating local conceptual summary ...

2025-07-27 22:41:12,875 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。
[❌code error localpattern agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-27 22:41:23,422 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:41:23,423 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-27 22:41:54,654 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error localpattern agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-27 22:42:00,799 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-27 22:42:34,078 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-27 22:42:57,938 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-27 22:43:09,713 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-27 22:43:26,405 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:26,405 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:26,406 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:26,406 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:26,406 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:26,407 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:52,517 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:52,823 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:54,615 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:43:54,819 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:44:00,811 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-27 22:44:05,726 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-27 22:44:21,291 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-27 22:44:48,063 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.
⚠️ [localtransform]Skipping. All newly generated features have been evaluated.
📝 [localpattern] Generating local conceptual summary ...

2025-07-27 22:45:02,303 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-27 22:45:15,412 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.19053878479533726
total_tokens	 105