In [1]:
from data_file.Student_Score import Student_Score as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Student_Score"
task = "classification"

2025-08-04 15:46:48,922 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.978809  0.978585  0.977020  0.978138  0.000796
DFS           0.977197  0.976919  0.976482  0.976866  0.000294
AutoFeat      0.978809  0.978585  0.977020  0.978138  0.000796
OpenFE        0.982867  0.983328  0.983171  0.983122  0.000191
CAAFE         0.978910  0.980313  0.979686  0.979636  0.000574
OCTree        0.978809  0.978585  0.977020  0.978138  0.000796
LLMFE         0.981271  0.980577  0.971984  0.977944  0.004224

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.978809  0.978585  0.977020  0.978138  0.000796
MALMAS(ours)  0.980914  0.983336  0.980704  0.981651  0.001194

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.978809  0.978585  0.977020  0.978138  0.000796
MALMAS(ours)  0.978949  0.980341  0.978672  0.979321  0.000730
MALMAS(ours)  0.979582  0.980782  0.979415  0.979926  0.000609
MALMAS(ours)  0.981359  0.979425  0.978932  0.979905  0.001047
MALMAS(ours)  0.983435  0.982657  0.974671  0.980254  0.003961
MALMAS(ours)  0.980914  0.983336  0.980704  0.981651  0.001194
MALMAS(ours)  0.981699  0.981551  0.982428  0.981892  0.000383

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.978809  0.978585  0.977020  0.978138  0.000796
DFS           0.977197  0.976919  0.976482  0.976866  0.000294
AutoFeat      0.978809  0.978585  0.977020  0.978138  0.000796
OpenFE        0.982867  0.983328  0.983171  0.983122  0.000191
CAAFE         0.978045  0.978777  0.979365  0.978729  0.000540
OCTree        0.978809  0.978585  0.977020  0.978138  0.000796
LLMFE         0.977279  0.978545  0.978533  0.978119  0.000594

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.978809  0.978585  0.977020  0.978138  0.000796
MALMAS(ours)  0.984378  0.983933  0.984901  0.984404  0.000396

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.931896  0.932652  0.925842  0.930130  0.003048
DFS           0.934166  0.926977  0.926220  0.929121  0.003581
AutoFeat      0.931896  0.932652  0.925842  0.930130  0.003048
OpenFE        0.936814  0.939463  0.942111  0.939463  0.002162
CAAFE         0.933409  0.931896  0.935679  0.933661  0.001555
OCTree        0.931896  0.932652  0.925842  0.930130  0.003048
LLMFE         0.934922  0.929247  0.927355  0.930508  0.003215

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.931896  0.932652  0.925842  0.930130  0.003048
MALMAS(ours)  0.939841  0.943625  0.944760  0.942742  0.002103

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.981450  0.982055  0.980393  0.981299  0.000687
DFS            0.978910  0.978940  0.979648  0.979166  0.000341
AutoFeat       0.981450  0.982055  0.980393  0.981299  0.000687
OpenFE         0.983769  0.983551  0.983268  0.983529  0.000205
CAAFE          0.981909  0.981849  0.979947  0.981235  0.000911
OCTree         0.981450  0.982055  0.980393  0.981299  0.000687
LLMFE          0.980371  0.981162  0.980424  0.980652  0.000361

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.981450  0.982055  0.980393  0.981299  0.000687
MALMAS(ours)   0.986421  0.985545  0.985848  0.985938  0.000363

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.989314  0.987860  0.987940  0.988371  0.000667
DFS            0.987544  0.986105  0.986943  0.986864  0.000590
AutoFeat       0.989314  0.988688  0.987940  0.988647  0.000562
OpenFE         0.989799  0.988903  0.990587  0.989763  0.000688
CAAFE          0.988789  0.989022  0.989198  0.989003  0.000168
OCTree         0.989314  0.987860  0.987940  0.988371  0.000667
LLMFE          0.988320  0.988253  0.988263  0.988279  0.000030

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.989314  0.987860  0.987940  0.988371  0.000667
MALMAS(ours)   0.990654  0.989125  0.991181  0.990320  0.000872

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.966737  0.964124  0.963366  0.964742  0.001444
DFS                 0.950622  0.951391  0.953572  0.951861  0.001250
AutoFeat            0.966737  0.963163  0.963366  0.964422  0.001639
OpenFE              0.960565  0.959832  0.961729  0.960709  0.000781
CAAFE               0.968093  0.959025  0.958487  0.961868  0.004407
OCTree              0.966737  0.964124  0.963366  0.964742  0.001444
LLMFE               0.962169  0.961137  0.960245  0.961184  0.000786

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.966737  0.964124  0.963366  0.964742  0.001444
MALMAS(ours)        0.968722  0.969096  0.968772  0.968863  0.000166

In [2]:
import time
set_params(compute_tokens=False)
time.sleep(3600)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Student_Score

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 10:17:35,777 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:17:35,798 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:17:35,799 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:17:35,799 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:17:35,800 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:17:35,984 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:18:02,836 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:18:08,827 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:18:13,898 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:18:22,855 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 10:18:36,528 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error unaryfeature agent] 'Current_Score'

2025-07-28 10:18:36,987 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:18:54,547 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [crosscompositional]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 10:19:18,971 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error localtransform agent] Cannot set a frame with no defined index and a val

2025-07-28 10:19:34,434 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:20:34,435 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 10:21:24,816 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 10:21:34,544 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:21:34,545 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:21:34,546 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:21:34,546 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:21:34,546 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:21:34,546 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:22:02,396 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:22:04,907 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:22:06,132 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:22:09,565 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:22:11,509 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] can only concatenate str (not "float") to str

2025-07-28 10:22:31,786 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error temporalfeature agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:22:49,502 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:22:49,503 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:23:05,269 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:23:33,482 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:23:44,557 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
[❌code error unaryfeature agent] could not convert string to float: 'Low'

2025-07-28 10:24:00,361 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] can only concatenate str (not "float") to str

2025-07-28 10:24:16,233 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 10:25:20,540 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] can only concatenate str (not "float") to str

2025-07-28 10:26:00,168 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] can only concatenate str (not "float") to str

2025-07-28 10:26:44,200 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] can only concatenate str (not "float") to str

2025-07-28 10:27:27,101 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:27:57,267 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [crosscompositional]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 10:28:57,628 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 3-th round =====

2025-07-28 10:29:07,666 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:07,667 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:07,673 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:07,680 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:07,694 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:07,882 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:35,925 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:36,028 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:40,383 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:41,865 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:50,416 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:29:56,611 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 10:30:18,933 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [localpattern]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:31:00,201 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 10:31:36,043 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:32:10,242 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 10:32:19,151 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 10:32:31,644 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:32:31,644 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:32:31,646 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:32:31,647 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:32:31,648 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:32:31,746 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:32:48,591 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:33:01,442 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [temporalfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 10:33:10,456 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:33:10,659 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:33:15,061 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 10:33:22,946 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 10:33:37,079 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 10:33:58,785 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 10:34:09,641 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 10:34:38,107 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 10:35:12,309 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 10:35:40,366 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 10:35:49,276 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.0
total_tokens	 153

In [3]:
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

total_times	 0.3104121149248547
total_tokens	 153