In [1]:
from data_file.Titanic import Titanic as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.model_factory import set_params, get_model
from main_demo.main_func import *
from main_demo.pipeline import *

prompt_path_list = global_config.prompt_path_list
task_name = "Titanic"
task = "classification"

2025-08-04 15:47:31,587 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.840729  0.835686  0.852814  0.843076  0.007187
DFS           0.846267  0.836603  0.834106  0.838992  0.005244
AutoFeat      0.840729  0.835686  0.852814  0.843076  0.007187
OpenFE        0.809647  0.821455  0.816212  0.815771  0.004831
CAAFE         0.858637  0.833333  0.855860  0.849277  0.011330
OCTree        0.840729  0.835686  0.852814  0.843076  0.007187
LLMFE         0.847224  0.833333  0.857833  0.846130  0.010032

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.840729  0.835686  0.852814  0.843076  0.007187
MALMAS(ours)  0.857999  0.852553  0.854873  0.855142  0.002231

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.840729  0.835686  0.852814  0.843076  0.007187
MALMAS(ours)  0.873758  0.835636  0.858231  0.855875  0.015652
MALMAS(ours)  0.872751  0.837204  0.866295  0.858750  0.015462
MALMAS(ours)  0.845361  0.851318  0.859857  0.852179  0.005949
MALMAS(ours)  0.875671  0.856256  0.863076  0.865001  0.008042
MALMAS(ours)  0.869965  0.853854  0.860290  0.861370  0.006622
MALMAS(ours)  0.884365  0.859560  0.860204  0.868043  0.011545

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.840729  0.835686  0.852814  0.843076  0.007187
DFS           0.846267  0.836603  0.834106  0.838992  0.005244
AutoFeat      0.840729  0.835686  0.852814  0.843076  0.007187
OpenFE        0.809647  0.821455  0.816212  0.815771  0.004831
CAAFE         0.846368  0.834968  0.847934  0.843090  0.005778
OCTree        0.842206  0.848348  0.850755  0.847103  0.003599
LLMFE         0.850379  0.842693  0.853074  0.848715  0.004398

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.840729  0.835686  0.852814  0.843076  0.007187
MALMAS(ours)  0.881176  0.861745  0.873910  0.872277  0.008016

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.719888  0.798319  0.784314  0.767507  0.034154
DFS           0.784314  0.778711  0.781513  0.781513  0.002287
AutoFeat      0.719888  0.798319  0.784314  0.767507  0.034154
OpenFE        0.711485  0.770308  0.644258  0.708683  0.051498
CAAFE         0.745098  0.792717  0.784314  0.774043  0.020753
OCTree        0.801120  0.803922  0.725490  0.776844  0.036331
LLMFE         0.753501  0.798319  0.789916  0.780579  0.019452

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.719888  0.798319  0.784314  0.767507  0.034154
MALMAS(ours)  0.820728  0.806723  0.820728  0.816060  0.006602

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.825792  0.848782  0.851378  0.841984  0.011498
DFS            0.841065  0.835969  0.848193  0.841742  0.005013
AutoFeat       0.825792  0.848782  0.851378  0.841984  0.011498
OpenFE         0.844623  0.831031  0.853316  0.842990  0.009171
CAAFE          0.853652  0.842743  0.848712  0.848369  0.004460
OCTree         0.849171  0.849850  0.848332  0.849117  0.000621
LLMFE          0.860634  0.846880  0.855254  0.854256  0.005659

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.825792  0.848782  0.851378  0.841984  0.011498
MALMAS(ours)   0.889769  0.860394  0.877890  0.876018  0.012065

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.872180  0.852986  0.856223  0.860463  0.008390
DFS            0.854592  0.846413  0.845874  0.848960  0.003989
AutoFeat       0.872180  0.848448  0.852866  0.857832  0.010305
OpenFE         0.878659  0.859560  0.859615  0.865944  0.008990
CAAFE          0.884466  0.846413  0.855150  0.862010  0.016274
OCTree         0.877551  0.869136  0.858404  0.868364  0.007836
LLMFE          0.884063  0.863897  0.860896  0.869619  0.010287

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.872180  0.852986  0.856223  0.860463  0.008390
MALMAS(ours)   0.898228  0.872439  0.860238  0.876968  0.015836

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.868169  0.845495  0.846013  0.853226  0.010569
DFS                 0.844220  0.813564  0.835906  0.831230  0.012945
AutoFeat            0.868169  0.858825  0.860446  0.862480  0.004077
OpenFE              0.816914  0.799533  0.845840  0.820762  0.019100
CAAFE               0.894972  0.851218  0.857071  0.867754  0.019394
OCTree              0.866424  0.862846  0.851724  0.860331  0.006259
LLMFE               0.891682  0.861461  0.863163  0.872102  0.013863

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.868169  0.845495  0.846013  0.853226  0.010569
MALMAS(ours)        0.909305  0.869870  0.858265  0.879147  0.021845

In [2]:
import time
set_params(compute_tokens=False)

start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Titanic

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 11:12:09,574 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:09,576 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:09,576 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:09,585 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:09,590 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:09,592 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:37,118 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:40,394 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:42,802 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:42,907 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:48,381 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:12:49,098 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:13:01,440 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 11:13:30,992 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [localpattern]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 11:14:11,685 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 11:14:19,824 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 11:14:36,209 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:36,210 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:36,210 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:36,211 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:36,211 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:36,215 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:53,923 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:14:58,783 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:15:02,611 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:15:09,795 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:15:16,656 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:15:28,022 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 11:15:35,245 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:15:45,383 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localtransform]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.
⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 11:16:19,837 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 11:16:38,066 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:16:48,612 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

🔁  ===== The 3-th round =====

2025-07-28 11:17:04,786 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:04,788 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:04,793 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:04,798 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:04,800 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:04,805 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:25,061 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:27,723 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:32,795 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:36,529 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:17:37,041 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 11:17:59,211 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...
⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.

2025-07-28 11:18:09,401 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 11:18:24,158 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 11:18:51,487 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [localpattern]Skipping. All newly generated features have been evaluated.

📝  Generating global conceptual summary...

2025-07-28 11:19:01,214 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 11:19:17,599 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:17,603 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:17,604 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:17,604 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:17,604 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:17,605 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:41,151 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:42,072 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:43,114 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:44,883 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:46,475 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:19:53,541 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [unaryfeature]Effective feature count 1 is less than min_effective(2), skipping LLM-generated conceptual summary.
📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:20:19,040 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [aggregationconstruct] Generating local conceptual summary ...

2025-07-28 11:20:43,205 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:21:06,449 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 11:21:30,461 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:21:41,471 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error crosscompositional agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。
📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 11:22:26,014 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 11:22:37,497 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.17929769734541576
total_tokens	 94