In [1]:
from data_file.Wine_Quality import Wine_Quality as read_data
from baselines.baseline_func import run_baseline_experiments
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Wine_Quality"
task = "classification"

2025-08-04 15:48:03,626 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
from baselines.baseline_func import run_baseline_experiments_for_other_model
baseline_summary_auc = run_baseline_experiments_for_other_model(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    other_model="gpt_41_mini",
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.876835  0.878248  0.879471  0.878185  0.001077
DFS           0.878029  0.884605  0.891285  0.884639  0.005412
AutoFeat      0.876835  0.878248  0.880815  0.878633  0.001647
OpenFE        0.881203  0.895311  0.896661  0.891058  0.006990
CAAFE         0.874938  0.874846  0.884469  0.878085  0.004515
OCTree        0.876835  0.878248  0.879471  0.878185  0.001077
LLMFE         0.878261  0.877643  0.880330  0.878745  0.001149

In [3]:
MALMAS_summary_auc_gpt4o = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    
    temp=1.0,
    other_model="gpt_41_mini",
    verbose=False
    
)
MALMAS_summary_auc_gpt4o

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.876835  0.878248  0.879471  0.878185  0.001077
MALMAS(ours)  0.881248  0.884947  0.881112  0.882435  0.001777

In [4]:
from main_demo.ablations import MALMAS_random_experiments_without_memory_async
res = pd.DataFrame()
for i in range(len(prompt_path_list)):
    prompt_path_sublist = prompt_path_list[:i+1]
    r = await MALMAS_random_experiments_without_memory_async(
        task_name=task_name,
        task=task,
        read_data_class=read_data,
        model_name="xgboost",
        metric="auc",
        prompt_path_list=prompt_path_sublist,
        Nround=4,
        
        temp=1.0,
        verbose=False,
        placeholder=i+1
    )
    if i == 0:
        res = pd.concat([res, r], axis=0)
    else:
        res = pd.concat([res, r[1:]], axis=0)

res

[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.
[MALMAS Ablation] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.876835  0.878248  0.879471  0.878185  0.001077
MALMAS(ours)  0.878558  0.880118  0.877573  0.878750  0.001047
MALMAS(ours)  0.878663  0.884310  0.880455  0.881143  0.002356
MALMAS(ours)  0.878821  0.882441  0.880853  0.880705  0.001482
MALMAS(ours)  0.879139  0.887749  0.880321  0.882403  0.003811
MALMAS(ours)  0.876018  0.884674  0.881494  0.880729  0.003575
MALMAS(ours)  0.879962  0.886581  0.883087  0.883210  0.002704

In [5]:
baseline_summary_auc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.876835  0.878248  0.879471  0.878185  0.001077
DFS           0.878029  0.884605  0.891285  0.884639  0.005412
AutoFeat      0.876835  0.878248  0.880815  0.878633  0.001647
OpenFE        0.881203  0.895311  0.896661  0.891058  0.006990
CAAFE         0.876679  0.879535  0.878478  0.878231  0.001179
OCTree        0.864071  0.878248  0.865087  0.869135  0.006457
LLMFE         0.875002  0.879575  0.882429  0.879002  0.003059

In [6]:
MALMAS_summary_auc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.876835  0.878248  0.879471  0.878185  0.001077
MALMAS(ours)  0.881895  0.888528  0.887470  0.885964  0.002910

In [7]:
baseline_summary_acc = run_baseline_experiments(
    
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="acc",
    verbose=False
)
baseline_summary_acc

                     0         1         2      mean       std
xgboost_base  0.859177  0.860716  0.861485  0.860459  0.000960
DFS           0.863024  0.862639  0.878415  0.868026  0.007348
AutoFeat      0.859177  0.860716  0.863024  0.860972  0.001581
OpenFE        0.865333  0.871489  0.879184  0.872002  0.005666
CAAFE         0.859561  0.860716  0.871104  0.863794  0.005191
OCTree        0.853020  0.860716  0.848018  0.853918  0.005222
LLMFE         0.861485  0.863024  0.864179  0.862896  0.001103

In [8]:
MALMAS_summary_acc = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="acc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_acc

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.859177  0.860716  0.861485  0.860459  0.000960
MALMAS(ours)  0.866102  0.869565  0.871489  0.869052  0.002229

In [9]:
baseline_summary_auc_m = run_baseline_experiments(
    
    task=task,
    model_name="lightgbm",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_m

                      0         1         2      mean       std
lightgbm_base  0.886117  0.885756  0.884996  0.885623  0.000467
DFS            0.883231  0.892794  0.892980  0.889668  0.004552
AutoFeat       0.886117  0.885756  0.885844  0.885906  0.000153
OpenFE         0.883852  0.896008  0.897363  0.892408  0.006075
CAAFE          0.883459  0.888791  0.882112  0.884788  0.002884
OCTree         0.866816  0.885756  0.868565  0.873713  0.008546
LLMFE          0.880985  0.890062  0.883532  0.884859  0.003823

In [10]:
MALMAS_summary_auc_m = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="lightgbm",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_m

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
lightgbm_base  0.886117  0.885756  0.884996  0.885623  0.000467
MALMAS(ours)   0.882622  0.889574  0.887260  0.886485  0.002890

In [11]:
baseline_summary_auc_c = run_baseline_experiments(
    
    task=task,
    model_name="mlp",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_c

                      0         1         2      mean       std
mlp_base  0.873778  0.883299  0.882682  0.879920  0.004350
DFS            0.877274  0.886743  0.887348  0.883789  0.004613
AutoFeat       0.873778  0.883299  0.880889  0.879322  0.004042
OpenFE         0.879900  0.888086  0.894065  0.887350  0.005806
CAAFE          0.873771  0.881363  0.878969  0.878034  0.003169
OCTree         0.864346  0.883299  0.867751  0.871799  0.008250
LLMFE          0.876211  0.883894  0.880732  0.880279  0.003153

In [12]:
MALMAS_summary_auc_c = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="mlp",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_c

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                      0         1         2      mean       std
mlp_base  0.873778  0.883299  0.882682  0.879920  0.004350
MALMAS(ours)   0.873246  0.884282  0.882731  0.880086  0.004878

In [13]:
baseline_summary_auc_r = run_baseline_experiments(
    
    task=task,
    model_name="random_forest",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc_r

                           0         1         2      mean       std
random_forest_base  0.890632  0.905687  0.899354  0.898558  0.006172
DFS                 0.889231  0.900688  0.900255  0.896724  0.005302
AutoFeat            0.890632  0.905687  0.901568  0.899296  0.006353
OpenFE              0.884581  0.896795  0.896735  0.892703  0.005744
CAAFE               0.891126  0.906088  0.901743  0.899652  0.006284
OCTree              0.874420  0.905687  0.883481  0.887863  0.013135
LLMFE               0.887846  0.903003  0.896516  0.895788  0.006209

In [14]:
MALMAS_summary_auc_r = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="random_forest",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_auc_r

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                           0         1         2      mean       std
random_forest_base  0.890632  0.905687  0.899354  0.898558  0.006172
MALMAS(ours)        0.884844  0.896412  0.898268  0.893175  0.005939

In [2]:
import time
set_params(compute_tokens=False)
time.sleep(1000)
start=time.time()
await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="auc",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    random_states_list=[100],
    temp=1.0,
    verbose=False
)
end=time.time()
print("total_times\t",(end-start)/3600)

print("total_tokens\t",global_config.total_tokens//1000)

Loaded local folder: D:\code_management\idea\mypro\data_file\Wine_Quality

================ Initialized AgentMemory ================


🔁  ===== The 1-th round =====

2025-07-28 11:36:37,678 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:36:37,680 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:36:37,680 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:36:37,681 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:36:37,681 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:36:37,682 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:37:07,066 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:37:12,084 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:37:16,487 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:37:21,928 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.

2025-07-28 11:37:40,503 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:37:49,869 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 11:38:17,463 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 11:38:40,709 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:38:49,363 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 11:39:16,806 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 11:40:16,752 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 11:40:25,823 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 2-th round =====

2025-07-28 11:40:39,033 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:40:39,034 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:40:39,036 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:40:40,058 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:40:40,058 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:40:40,063 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:41:04,326 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:41:05,145 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:41:10,471 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:41:13,032 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:41:20,307 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:41:24,913 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:41:46,207 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Skipping. All newly generated features have been evaluated.
[❌code error localtransform agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 11:41:55,731 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 11:42:31,365 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [crosscompositional]Skipping. All newly generated features have been evaluated.
📝 [localpattern] Generating local conceptual summary ...

2025-07-28 11:43:11,096 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:43:18,783 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error localtransform agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。
[❌code error localtransform agent] ❌ 编译阶段出错。llm-code原因错误SyntaxError: invalid syntax。

2025-07-28 11:43:45,810 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:44:21,548 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 11:45:17,714 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:45:26,568 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

🔁  ===== The 3-th round =====

2025-07-28 11:45:40,186 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:45:40,187 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:45:40,188 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:45:40,188 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:45:40,200 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:45:40,392 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:46:07,942 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:46:17,972 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:46:24,324 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:46:24,575 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:46:24,833 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:46:54,991 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:47:04,359 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 11:47:39,278 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 11:48:41,536 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error aggregationconstruct agent] '<lambda>'

2025-07-28 11:48:49,426 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 11:49:15,484 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 11:50:08,678 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

⚠️ [aggregationconstruct]Effective feature count 0 is less than min_effective(2), skipping LLM-generated conceptual summary.

📝  Generating global conceptual summary...

2025-07-28 11:51:12,270 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

🔁  ===== The 4-th round =====

2025-07-28 11:51:26,096 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:51:26,108 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:51:26,109 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:51:26,195 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:51:26,204 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:51:26,210 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:51:55,687 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:52:02,241 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:52:02,649 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:52:04,958 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:52:14,528 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2025-07-28 11:52:14,529 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [temporalfeature] Generating local conceptual summary ...

2025-07-28 11:52:57,283 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [crosscompositional] Generating local conceptual summary ...

2025-07-28 11:53:56,421 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

[❌code error localtransform agent] data type 'category' not understood
⚠️ [aggregationconstruct]Skipping. All newly generated features have been evaluated.

2025-07-28 11:54:05,734 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localpattern] Generating local conceptual summary ...

2025-07-28 11:55:16,189 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [unaryfeature] Generating local conceptual summary ...

2025-07-28 11:56:24,895 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝 [localtransform] Generating local conceptual summary ...

2025-07-28 11:57:21,932 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

📝  Generating global conceptual summary...

2025-07-28 11:57:33,504 INFO: HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

total_times	 0.3535873599847158
total_tokens	 144